### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [RyanKaltenbach/prj-rev-bwfs-dasmoto#7]
https://github.com/RyanKaltenbach/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/assets/style.css#L9-L20

There is way too much repetition going on in your CSS rules.

When you have some styles that need to get applied to several elements, write them in a single rule with a more general selector. 

```css
* {
  font-family: Helvetica;
}

.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

.brushes {
  background-color: mediumspringgreen;
}
```
